# Generated by Django 5.1.7 on 2025-03-14 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=3, default=0, max_digits=19),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=3, default=0, max_digits=19),
                ),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")], max_length=8
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=19)),
                ("external_id", models.CharField(max_length=64, unique=True)),
                (
                    "credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="credits",
                        to="debitcredit.account",
                    ),
                ),
                (
                    "debit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="debits",
                        to="debitcredit.account",
                    ),
                ),
            ],
        ),
    ]
